### ISSUE TITLE
US #5: Yelp Review Component

### ISSUE THREAD

**Issue by SamvritSrinath** [cse110-sp24-group7/warmup-exercise#6]
## Description

Given a number(representing a user's mood); generate a set of fake Yelp Reviews with a similar rating/feeling to the rating(i.e. a super happy reflection of a day for 7, and a very depressing reflection for 1). This will need an affiliated `.js` file. Then format and render this accordingly with `html, css` similar to Yelp. 

## Frontend

Take a look at Yelp.com to get an idea. This should be rendered solely off a number. See if you can generate 5 Yelp Reviews that fade in from the bottom of the screen('css' animations). Take a look at this documentation for custom components: https://www.freecodecamp.org/news/reusable-html-components-how-to-reuse-a-header-and-footer-on-a-website;.

## Backend

N/A

**Comment by andronius-yang** [comment]
@SamvritSrinath Pushed basic updates of review container + slide in animation. Unsure if formatting requirements are met. Still require random message generation.
